<?php

namespace App\Controllers;
use App\Models\PublicModel;
use CodeIgniter\HTTP\RedirectResponse;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class PublicController extends BaseController
{
    private PublicModel $pbl;
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->pbl= model(PublicModel::class);
    }
    public function MainList($id=false,$pg=0):string|RedirectResponse{
        $page['data']["title"]= "Электронный научный архив МелГУ: Главаня страница";

        if($this->session->has("collectionsFilter"))
            $page['data']['filter']= $this->session->get("MainFilter");

        $page['data']['edSections']= $this->pbl->getSectionsList();

        $page['pageContent']= view("public/main",$page['data']);
        return view("public/page",$page);
    }
    public function ChapterList($id=false,$pg=0):string|RedirectResponse{
        $page['data']["title"]= "Электронный научный архив МелГУ: ";

        if($this->session->has("collectionsFilter"))
            $page['data']['filter']= $this->session->get("MainFilter");

        $page['data']['edSections']= $this->pbl->getChapterList($id);
        $page['data']['TitleSections']= $this->pbl->getTitleSection($id);
        $page['data']['edCollections']= $this->pbl->getCollectionsList($id);

        $l = $this->pbl->db->table('sections')->where(['parent'=>$id])->get()->getResult();
        $count=  $this->pbl->db
            ->table("publications")
            ->get()->getNumRows();
        $maxPages= ceil($count / 20);

        if($maxPages<$pg) $pg = $maxPages;
        if($pg<1) $pg = 1;

        $page['data']['paginator']= view("admin/template/paginator",[
            "maxPages"=>$maxPages,
            "currentPage"=>$pg,
            "baseLink"=>base_url("/collections/$id/page-"),
        ]);

        $list = $this->pbl->db->table('publications')
            ->where("JSON_CONTAINS(sections, '\"".$id."\"', '$')")
            ->limit(20,($pg-1)*20)
            ->get()->getResult();


        if(empty($l)){
            $page['data']['publications']= view("public/publications",["list"=>$list,"paginator"=>$page['data']['paginator']]);
            $page['pageContent']= view("public/subchapter",$page['data']);
            return view("public/page",$page);
        }
        else{
            $page['data']['publications']= view("public/publications",["list"=>$list,"paginator"=>$page['data']['paginator']]);
            $page['pageContent']= view("public/chapter",$page['data']);
            return view("public/page",$page);
        }

    }

    public function CollectList($id=false,$pg=0):string|RedirectResponse{
        $page['data']["title"]= "Электронный научный архив МелГУ: ";

        if($this->session->has("collectionsFilter"))
            $page['data']['filter']= $this->session->get("MainFilter");

        $count=  $this->pbl->db
            ->table("publications")
            ->get()->getNumRows();
        $maxPages= ceil($count / 20);

        if($maxPages<$pg) $pg = $maxPages;
        if($pg<1) $pg = 1;

        $page['data']['paginator']= view("admin/template/paginator",[
            "maxPages"=>$maxPages,
            "currentPage"=>$pg,
            "baseLink"=>base_url("/collections/$id/page-"),
        ]);

        $list = $this->pbl->db->table('publications')
            ->where("JSON_CONTAINS(collections, '\"".$id."\"', '$')")
            ->limit(20,($pg-1)*20)
            ->get()->getResult();

        $page['data']['edCollections']= $this->pbl->getTitleCollection($id);
        $page['data']['publications']= view("public/publications",["list"=>$list,"paginator"=>$page['data']['paginator']]);
        $page['pageContent']= view("public/collections",$page['data']);
        return view("public/page",$page);
    }
    public function CollectionsList($id=false,$pg=0):string|RedirectResponse{
        $page['data']["title"]= "Электронный научный архив МелГУ: ";

        if($this->session->has("collectionsFilter"))
            $page['data']['filter']= $this->session->get("MainFilter");

        $page['data']['edCollections']= $this->pbl->getCollectionsList($id);
        $page['data']['TitleChapter']= $this->pbl->getSubTitleChapter($id);


        $page['pageContent']= view("public/subchapter",$page['data']);
        return view("public/page",$page);
    }
    public function Publication($id=false,$pg=0):string|RedirectResponse{
        $page['data']["title"]= "Электронный научный архив МелГУ: ";

        if($this->session->has("collectionsFilter"))
            $page['data']['filter']= $this->session->get("MainFilter");

        $page['data']['Publicate']= $this->pbl->getPublication($id);
        $page['data']['TitleChapter']= $this->pbl->getSubTitleChapter($id);

        $page['pageContent']= view("public/publication",$page['data']);
        return view("public/page",$page);
    }


}
