<?php

namespace App\Controllers;
use App\Models\SourcesModel;
use CodeIgniter\HTTP\RedirectResponse;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class SourcesController extends BaseController
{
    private SourcesModel $sm;
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->sm= model(SourcesModel::class);
    }
    public function SourcesList($sm= false):string|RedirectResponse{

        if($this->sm->hasAuth() === false)
            return view("admin/template/page",["pageContent"=>view("admin/User/Auth")]);
        //dd($this->model->createPassword("aRf8zKl1s1"));
        $page['data']['includes']=(object)[
            'js'=>["/js/admin/change-visible.js"],
            'css'=>["/css/admin/collections.css","/css/admin/sections.css"],
        ];
        $page['data']["title"]= "Control Panel: Источники";
        $page['menuTop']= view("admin/template/menuTop",["menu"=>$this->model->getMenu("admin")]);

        if($this->session->has("sourcesFilter"))
            $page['data']['filter']= $this->session->get("sourcesFilter");
        $page['data']['filterSection']= view("admin/sources/FilterSection",$page['data']);

        $page['data']['edSource']= $this->sm->getSourcesList((array)($page['data']['filter']??[]));
        if($this->session->has("message"))
            $page['data']['message']= $this->session->getFlashdata("message");

        $page['pageContent']= view("admin/sources/ListView",$page['data']);
        return $sm?$page['pageContent']:view(ADMIN."/template/page",$page);
    }
    public function form($op= "add",$pID= false,$modal= false):string|RedirectResponse{
        if(!$this->sm->hasAuth()) return redirect()->to(base_url(ADMIN));
        if($op!=="add" && $pID===false) return redirect()->to(base_url("/admin/sources/"));
        $page['data']['includes']=(object)[
            'js'=>[],
            'css'=>["/css/admin/collections.css"],
        ];
        $page['data']["title"] = "Источник : ".(($op=="add")?"Создать":": Редактирование");
        $page['menuTop']= view("admin/template/menuTop",["menu"=>$this->model->getMenu("admin")]);
        $page['data']['op']= $op;
        $page['data']['pID']= $pID;

        if($this->session->has("form")){
            $page['data']['form']= (object)$this->session->getFlashdata("form");
            $page['data']['validator']= $this->session->getFlashdata("validator");
            $page['data']['errors'] = $this->sm->getFormErrors($page['data']['validator']);
        }
        elseif($op=="edit")
            $page['data']['form']= $this->sm->db->table('sources')->where(["id"=>$pID])->get()->getFirstRow();

        $page['pageContent']= view("admin/sources/FormView",$page['data']);
        return $modal?$page['pageContent']:view(ADMIN."/template/page",$page);
    }

    public function formProcessing(){
        if(!$this->sm->hasAuth()) return redirect()->to(base_url(ADMIN));
        $form= (object)$this->request->getVar('form');
        $rules= [
            //'form.code' => 'required|is_unique[edProfiles.code]',
            'form.title' => 'required|is_unique[Sources.title]',
        ];
      if($form->op=="edit") $rules['form.title']= "required|is_unique[sources.title, id, ".$form->id."]";
        $messages= [
            'form.title'=>[
                "required"=>"required",
                "is_unique"=>"Источник с именем $form->title уже существует"
            ],
        ];
        $inputs = $this->validate($rules,$messages);
        if (!$inputs) {
            $form= json_decode(json_encode($form), FALSE);
            $this->session->setFlashdata("form",$form);
            $this->session->setFlashdata("validator",$this->validator);
            if($form->op=="add")
                return redirect()->to(base_url("/admin/sources/add"));
            else
                return redirect()->to(base_url("/admin/sources/edit/".$form->id));
        }
        if($form->op=="add") $this->sm->SourcesAdd($form);
        if($form->op=="edit") $this->sm->SourcesChange($form);
        return redirect()->to(base_url("/admin/sources/"));
    }

    public function delete($id= false)
    {
        if (!$this->sm->hasAuth()) return redirect()->to(base_url(ADMIN));
        if (!$id) return redirect()->to(base_url("/admin/sources/"));
        $source = $this->sm->dbGetRow("sources", ["id" => $id]);
        if ($source->cnt == "") {
        $this->session->setFlashdata("message", (object)["type" => "success", "class" => "callout-success", "message" => "Источник удален: #$source->id: $source->title"]);
        $this->sm->dbDelete("sources", ["id" => $id]);
        }
        else
            $this->session->setFlashdata("message", (object)["type" => "error", "class" => "callout-error", "message" => "Источник не может быть удален так как в нем есть записи"]);
        return redirect()->to(base_url("/admin/sources/"));
    }
    public function changeVisible():string|bool{
        if(!$this->sm->hasAuth()) return json_encode(['message'=>"success denied"]);
        $form= (object)$this->request->getVar();
        $this->sm->dbUpdateFiled("sources",["display"=>(string)$form->display],["id"=>$form->id]);
        return true;
    }
    public function setFilter(){
        if(!$this->sm->hasAuth()) return json_encode(['message'=>"success denied"]);
        $filter= (object)$this->request->getVar('filter');
        $this->session->set("sourcesFilter",$filter);
        return redirect()->to(base_url("/admin/sources/"));
    }


}
